### ISSUE TITLE
Allocation dynamique dans la pile

### ISSUE THREAD

**Issue by P1K** [Antoxyde/isd#13]
https://github.com/Antoxyde/isd/blob/9525e280846c84d038ea9c41fb23d9a5e14ac84a/stern.c#L20

Pourquoi pas `comb1[p]` etc. ?

**Comment by Antoxyde** [comment]
En général et si j'ai le choix, je préfère allouer statiquement que dynamiquement dans la pile. 
Mais c'est vrai que ca rajoute de la "complexité visuelle" pour rien.
