### ISSUE TITLE
Stockage inutile ?

### ISSUE THREAD

**Issue by P1K** [Antoxyde/isd#21]
https://github.com/Antoxyde/isd/blob/9525e280846c84d038ea9c41fb23d9a5e14ac84a/stern.c#L227-L229

Est-ce bien nécessaire de stocker les combinaisons à ce stade là, puisqu'elles ne vont pas toutes être utiles par la suite ?
Idéalement il faudrait tester si ça ne va pas plus vite de juste les recalculer à la troisième passe

**Comment by Antoxyde** [comment]
J'ai fait le test, c'est légerement mieux effectivement.
J'ai merge ca dans 3pass du coup.
