### ISSUE TITLE
lc_indexes

### ISSUE THREAD

**Issue by P1K** [Antoxyde/isd#22]
Je comprends pas bien le rôle de `lc_indexes`:

https://github.com/Antoxyde/isd/blob/9525e280846c84d038ea9c41fb23d9a5e14ac84a/stern.c#L232

Pourquoi il devrait être différent en fonction des fenêtres ? La valeur qu'il prend à la fin de la première passe n'est elle pas constante, et juste fonction des paramètres du code et de l'algo ?

**Comment by Antoxyde** [comment]
Oui, c'est vrai que pour la 1ère passe on connait déjà la taille du tableau, c'est `nelem`.
Pour les passes suivantes par contre il me parait utile.

**Comment by P1K** [comment]
Oui, je l'ai vu après pour les deux dernières
